// flow-typed signature: a932262b5c81eb4f2ec1533075ab230d
// flow-typed version: <<STUB>>/ethereumjs-util_v^5.1.1/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ethereumjs-util'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'ethereumjs-util' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'ethereumjs-util/coverage/lcov-report/prettify' {
  declare module.exports: any;
}

declare module 'ethereumjs-util/coverage/lcov-report/sorter' {
  declare module.exports: any;
}

declare module 'ethereumjs-util/karma.conf' {
  declare module.exports: any;
}

declare module 'ethereumjs-util/test' {
  declare module.exports: any;
}

declare module 'ethereumjs-util/test/defineFields' {
  declare module.exports: any;
}

declare module 'ethereumjs-util/test/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'ethereumjs-util/coverage/lcov-report/prettify.js' {
  declare module.exports: $Exports<'ethereumjs-util/coverage/lcov-report/prettify'>;
}
declare module 'ethereumjs-util/coverage/lcov-report/sorter.js' {
  declare module.exports: $Exports<'ethereumjs-util/coverage/lcov-report/sorter'>;
}
declare module 'ethereumjs-util/index' {
  declare module.exports: $Exports<'ethereumjs-util'>;
}
declare module 'ethereumjs-util/index.js' {
  declare module.exports: $Exports<'ethereumjs-util'>;
}
declare module 'ethereumjs-util/karma.conf.js' {
  declare module.exports: $Exports<'ethereumjs-util/karma.conf'>;
}
declare module 'ethereumjs-util/test.js' {
  declare module.exports: $Exports<'ethereumjs-util/test'>;
}
declare module 'ethereumjs-util/test/defineFields.js' {
  declare module.exports: $Exports<'ethereumjs-util/test/defineFields'>;
}
declare module 'ethereumjs-util/test/index.js' {
  declare module.exports: $Exports<'ethereumjs-util/test/index'>;
}
