// flow-typed signature: e3ed211651b9f23e89a7a66ffb4b1b2e
// flow-typed version: <<STUB>>/truffle_v^3.2.2/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'truffle'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'truffle' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'truffle/cli' {
  declare module.exports: any;
}

declare module 'truffle/exec' {
  declare module.exports: any;
}

declare module 'truffle/lib/assertions' {
  declare module.exports: any;
}

declare module 'truffle/lib/build' {
  declare module.exports: any;
}

declare module 'truffle/lib/command' {
  declare module.exports: any;
}

declare module 'truffle/lib/commands/build' {
  declare module.exports: any;
}

declare module 'truffle/lib/commands/compile' {
  declare module.exports: any;
}

declare module 'truffle/lib/commands/console' {
  declare module.exports: any;
}

declare module 'truffle/lib/commands/create' {
  declare module.exports: any;
}

declare module 'truffle/lib/commands/deploy' {
  declare module.exports: any;
}

declare module 'truffle/lib/commands/digest' {
  declare module.exports: any;
}

declare module 'truffle/lib/commands/exec' {
  declare module.exports: any;
}

declare module 'truffle/lib/commands/index' {
  declare module.exports: any;
}

declare module 'truffle/lib/commands/init' {
  declare module.exports: any;
}

declare module 'truffle/lib/commands/install' {
  declare module.exports: any;
}

declare module 'truffle/lib/commands/migrate' {
  declare module.exports: any;
}

declare module 'truffle/lib/commands/networks' {
  declare module.exports: any;
}

declare module 'truffle/lib/commands/publish' {
  declare module.exports: any;
}

declare module 'truffle/lib/commands/serve' {
  declare module.exports: any;
}

declare module 'truffle/lib/commands/test' {
  declare module.exports: any;
}

declare module 'truffle/lib/commands/version' {
  declare module.exports: any;
}

declare module 'truffle/lib/commands/watch' {
  declare module.exports: any;
}

declare module 'truffle/lib/contracts' {
  declare module.exports: any;
}

declare module 'truffle/lib/copy' {
  declare module.exports: any;
}

declare module 'truffle/lib/create' {
  declare module.exports: any;
}

declare module 'truffle/lib/environment' {
  declare module.exports: any;
}

declare module 'truffle/lib/errors/builderror' {
  declare module.exports: any;
}

declare module 'truffle/lib/errors/configurationerror' {
  declare module.exports: any;
}

declare module 'truffle/lib/errors/deployerror' {
  declare module.exports: any;
}

declare module 'truffle/lib/errors/taskerror' {
  declare module.exports: any;
}

declare module 'truffle/lib/networks' {
  declare module.exports: any;
}

declare module 'truffle/lib/package' {
  declare module.exports: any;
}

declare module 'truffle/lib/repl' {
  declare module.exports: any;
}

declare module 'truffle/lib/require-nocache' {
  declare module.exports: any;
}

declare module 'truffle/lib/serve' {
  declare module.exports: any;
}

declare module 'truffle/lib/test' {
  declare module.exports: any;
}

declare module 'truffle/lib/testing/deployed' {
  declare module.exports: any;
}

declare module 'truffle/lib/testing/soliditytest' {
  declare module.exports: any;
}

declare module 'truffle/lib/testing/testresolver' {
  declare module.exports: any;
}

declare module 'truffle/lib/testing/testrunner' {
  declare module.exports: any;
}

declare module 'truffle/lib/testing/testsource' {
  declare module.exports: any;
}

declare module 'truffle/templates/example' {
  declare module.exports: any;
}

declare module 'truffle/templates/migration' {
  declare module.exports: any;
}

declare module 'truffle/test/compile' {
  declare module.exports: any;
}

declare module 'truffle/test/config' {
  declare module.exports: any;
}

declare module 'truffle/test/create' {
  declare module.exports: any;
}

declare module 'truffle/test/ethpm' {
  declare module.exports: any;
}

declare module 'truffle/test/migrate' {
  declare module.exports: any;
}

declare module 'truffle/test/npm' {
  declare module.exports: any;
}

declare module 'truffle/test/profiler' {
  declare module.exports: any;
}

declare module 'truffle/test/scenarios' {
  declare module.exports: any;
}

declare module 'truffle/test/scenarios/commandrunner' {
  declare module.exports: any;
}

declare module 'truffle/test/scenarios/contract_names/test_imports' {
  declare module.exports: any;
}

declare module 'truffle/test/scenarios/cyclic_dependencies/compiles' {
  declare module.exports: any;
}

declare module 'truffle/test/scenarios/happy_path/happypath' {
  declare module.exports: any;
}

declare module 'truffle/test/scenarios/memorylogger' {
  declare module.exports: any;
}

declare module 'truffle/test/scenarios/migrations/parameters' {
  declare module.exports: any;
}

declare module 'truffle/test/scenarios/reporter' {
  declare module.exports: any;
}

declare module 'truffle/test/scenarios/solidity_testing/with_balances' {
  declare module.exports: any;
}

// Filename aliases
declare module 'truffle/cli.js' {
  declare module.exports: $Exports<'truffle/cli'>;
}
declare module 'truffle/exec.js' {
  declare module.exports: $Exports<'truffle/exec'>;
}
declare module 'truffle/index' {
  declare module.exports: $Exports<'truffle'>;
}
declare module 'truffle/index.js' {
  declare module.exports: $Exports<'truffle'>;
}
declare module 'truffle/lib/assertions.js' {
  declare module.exports: $Exports<'truffle/lib/assertions'>;
}
declare module 'truffle/lib/build.js' {
  declare module.exports: $Exports<'truffle/lib/build'>;
}
declare module 'truffle/lib/command.js' {
  declare module.exports: $Exports<'truffle/lib/command'>;
}
declare module 'truffle/lib/commands/build.js' {
  declare module.exports: $Exports<'truffle/lib/commands/build'>;
}
declare module 'truffle/lib/commands/compile.js' {
  declare module.exports: $Exports<'truffle/lib/commands/compile'>;
}
declare module 'truffle/lib/commands/console.js' {
  declare module.exports: $Exports<'truffle/lib/commands/console'>;
}
declare module 'truffle/lib/commands/create.js' {
  declare module.exports: $Exports<'truffle/lib/commands/create'>;
}
declare module 'truffle/lib/commands/deploy.js' {
  declare module.exports: $Exports<'truffle/lib/commands/deploy'>;
}
declare module 'truffle/lib/commands/digest.js' {
  declare module.exports: $Exports<'truffle/lib/commands/digest'>;
}
declare module 'truffle/lib/commands/exec.js' {
  declare module.exports: $Exports<'truffle/lib/commands/exec'>;
}
declare module 'truffle/lib/commands/index.js' {
  declare module.exports: $Exports<'truffle/lib/commands/index'>;
}
declare module 'truffle/lib/commands/init.js' {
  declare module.exports: $Exports<'truffle/lib/commands/init'>;
}
declare module 'truffle/lib/commands/install.js' {
  declare module.exports: $Exports<'truffle/lib/commands/install'>;
}
declare module 'truffle/lib/commands/migrate.js' {
  declare module.exports: $Exports<'truffle/lib/commands/migrate'>;
}
declare module 'truffle/lib/commands/networks.js' {
  declare module.exports: $Exports<'truffle/lib/commands/networks'>;
}
declare module 'truffle/lib/commands/publish.js' {
  declare module.exports: $Exports<'truffle/lib/commands/publish'>;
}
declare module 'truffle/lib/commands/serve.js' {
  declare module.exports: $Exports<'truffle/lib/commands/serve'>;
}
declare module 'truffle/lib/commands/test.js' {
  declare module.exports: $Exports<'truffle/lib/commands/test'>;
}
declare module 'truffle/lib/commands/version.js' {
  declare module.exports: $Exports<'truffle/lib/commands/version'>;
}
declare module 'truffle/lib/commands/watch.js' {
  declare module.exports: $Exports<'truffle/lib/commands/watch'>;
}
declare module 'truffle/lib/contracts.js' {
  declare module.exports: $Exports<'truffle/lib/contracts'>;
}
declare module 'truffle/lib/copy.js' {
  declare module.exports: $Exports<'truffle/lib/copy'>;
}
declare module 'truffle/lib/create.js' {
  declare module.exports: $Exports<'truffle/lib/create'>;
}
declare module 'truffle/lib/environment.js' {
  declare module.exports: $Exports<'truffle/lib/environment'>;
}
declare module 'truffle/lib/errors/builderror.js' {
  declare module.exports: $Exports<'truffle/lib/errors/builderror'>;
}
declare module 'truffle/lib/errors/configurationerror.js' {
  declare module.exports: $Exports<'truffle/lib/errors/configurationerror'>;
}
declare module 'truffle/lib/errors/deployerror.js' {
  declare module.exports: $Exports<'truffle/lib/errors/deployerror'>;
}
declare module 'truffle/lib/errors/taskerror.js' {
  declare module.exports: $Exports<'truffle/lib/errors/taskerror'>;
}
declare module 'truffle/lib/networks.js' {
  declare module.exports: $Exports<'truffle/lib/networks'>;
}
declare module 'truffle/lib/package.js' {
  declare module.exports: $Exports<'truffle/lib/package'>;
}
declare module 'truffle/lib/repl.js' {
  declare module.exports: $Exports<'truffle/lib/repl'>;
}
declare module 'truffle/lib/require-nocache.js' {
  declare module.exports: $Exports<'truffle/lib/require-nocache'>;
}
declare module 'truffle/lib/serve.js' {
  declare module.exports: $Exports<'truffle/lib/serve'>;
}
declare module 'truffle/lib/test.js' {
  declare module.exports: $Exports<'truffle/lib/test'>;
}
declare module 'truffle/lib/testing/deployed.js' {
  declare module.exports: $Exports<'truffle/lib/testing/deployed'>;
}
declare module 'truffle/lib/testing/soliditytest.js' {
  declare module.exports: $Exports<'truffle/lib/testing/soliditytest'>;
}
declare module 'truffle/lib/testing/testresolver.js' {
  declare module.exports: $Exports<'truffle/lib/testing/testresolver'>;
}
declare module 'truffle/lib/testing/testrunner.js' {
  declare module.exports: $Exports<'truffle/lib/testing/testrunner'>;
}
declare module 'truffle/lib/testing/testsource.js' {
  declare module.exports: $Exports<'truffle/lib/testing/testsource'>;
}
declare module 'truffle/templates/example.js' {
  declare module.exports: $Exports<'truffle/templates/example'>;
}
declare module 'truffle/templates/migration.js' {
  declare module.exports: $Exports<'truffle/templates/migration'>;
}
declare module 'truffle/test/compile.js' {
  declare module.exports: $Exports<'truffle/test/compile'>;
}
declare module 'truffle/test/config.js' {
  declare module.exports: $Exports<'truffle/test/config'>;
}
declare module 'truffle/test/create.js' {
  declare module.exports: $Exports<'truffle/test/create'>;
}
declare module 'truffle/test/ethpm.js' {
  declare module.exports: $Exports<'truffle/test/ethpm'>;
}
declare module 'truffle/test/migrate.js' {
  declare module.exports: $Exports<'truffle/test/migrate'>;
}
declare module 'truffle/test/npm.js' {
  declare module.exports: $Exports<'truffle/test/npm'>;
}
declare module 'truffle/test/profiler.js' {
  declare module.exports: $Exports<'truffle/test/profiler'>;
}
declare module 'truffle/test/scenarios.js' {
  declare module.exports: $Exports<'truffle/test/scenarios'>;
}
declare module 'truffle/test/scenarios/commandrunner.js' {
  declare module.exports: $Exports<'truffle/test/scenarios/commandrunner'>;
}
declare module 'truffle/test/scenarios/contract_names/test_imports.js' {
  declare module.exports: $Exports<'truffle/test/scenarios/contract_names/test_imports'>;
}
declare module 'truffle/test/scenarios/cyclic_dependencies/compiles.js' {
  declare module.exports: $Exports<'truffle/test/scenarios/cyclic_dependencies/compiles'>;
}
declare module 'truffle/test/scenarios/happy_path/happypath.js' {
  declare module.exports: $Exports<'truffle/test/scenarios/happy_path/happypath'>;
}
declare module 'truffle/test/scenarios/memorylogger.js' {
  declare module.exports: $Exports<'truffle/test/scenarios/memorylogger'>;
}
declare module 'truffle/test/scenarios/migrations/parameters.js' {
  declare module.exports: $Exports<'truffle/test/scenarios/migrations/parameters'>;
}
declare module 'truffle/test/scenarios/reporter.js' {
  declare module.exports: $Exports<'truffle/test/scenarios/reporter'>;
}
declare module 'truffle/test/scenarios/solidity_testing/with_balances.js' {
  declare module.exports: $Exports<'truffle/test/scenarios/solidity_testing/with_balances'>;
}
